spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 484166861149-9dt7gks5gisuvj9gpoprvp83l13eh205.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
  datasource:
    url: jdbc:h2:mem:food
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8071